preload = /usr/share/sddm/themes/sddm-astronaut-theme/Backgrounds/astronaut.png
wallpaper = monitor,/usr/share/sddm/themes/sddm-astronaut-theme/Backgrounds/astronaut.png
# Use "ipc = off" for better battery, or "on" to change via command line
