general {
  lock_cmd = pidof hyprlock || hyprlock 	# avoid starting multiple instances
  before_sleep_cmd = loginctl lock-session 	# lock before suspend
  after_sleep_cmd = hyprctl dispatch dpms on 	# turn on display after sleep
}

# 5 min lock screen
listener {
  timeout = 300
  on-timeout = loginctl lock-session
}

# 5.5 min turn monitor off
listener {
  timeout = 330
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# 10 minutes suspend pc
listener {
  timeout = 600
  on-timeout = systemctl suspend
}
