#!/bin/bash

dateString=$(date '+%Y-%m-%d')
path=~/Documents/.writing/
[ ! -z "$1" ] && filename="$1.md" || filename=$dateString.md
filePath="$path/$filename"

if [ ! -f $filePath ]; then
    printf "Date: $dateString\nTags: " > $filePath
fi

vi $filePath -c 'Goyo'
